import os

from pathlib import Path
from glob import glob
from tqdm import tqdm
import dotenv
import random


configfile: "config.yaml"


include: "rules/supervisely.smk"


# include: "rules/convert_to_png.smk"


glob_str = expand(
    "{data_dir}/{folder}/{filename}{file_suffix}", **config, allow_missing=True
)[0]
folders, filenames = glob_wildcards(glob_str)


# def get_uploaded_annotations_list(wildcards):
#     # ck_output = checkpoints.convert_to_pngs.get(**wildcards).output
#     # return ck_output.folder
#     breakpoint()
#     # wildcards = glob_wildcards("results/{folder}/{filename}/i={i}_t={t}_z={z}_c={c}.png")
#     # # random.sample(zip(*wildcards),config["n_samples"]])

#     # breakpoint()
#     # uploaded_annotation_list = expand(
#     #     "results/{folder}/{filename}/i={i}_t={t}_z={z}_c={c}.uploaded",
#     #     zip,
#     #     filename=wildcards.filename,
#     #     folder=wildcards.folder,
#     #     i=wildcards.i,
#     #     t=wildcards.t,
#     #     z=wildcards.z,
#     #     c=wildcards.c,
#     # )
#     # breakpoint()
#     # return uploaded_annotation_list


def upload_subset_annotations(wildcards):
    checkpoints.all_converted.get(**wildcards).output
    wildcards = glob_wildcards(
        "results/{folder}/{filename}/i={i}_t={t}_z={z}_c={c}.png"
    )
    pngs = expand(
        "results/supervisely/{folder}/{filename}/i={i}_t={t}_z={z}_c={c}.uploaded.png",
        zip,
        **wildcards._asdict()
    )
    return random.Random(42).sample(pngs, config["image_samples"])
    # return sampled_pngs


rule all:
    input:
        expand(
            "results/{folder}/{filename}.converted.flag",
            folder=folders,
            filename=filenames,
        ),
        # get_uploaded_annotations_list,
        upload_subset_annotations,


rule upload_to_supervisley:
    input:
        png="results/{filename}/i={i}_t={t}_z={z}_c={c}.png",
    output:
        touch("results/supervisely/{filename}/i={i}_t={t}_z={z}_c={c}.uploaded.png"),
    params:
        address=config["supervisely"]["address"],
        token=config["supervisely"]["token"],
        workspace_id=config["supervisely"]["workspace_id"],
        workspace_name=config["supervisely"]["workspace_name"],
        dataset_name=config["supervisely"]["dataset_name"],
    script:
        "scripts/upload_to_supervisely.py"


rule convert_agg:
    input:
        checkpoint=lambda wildcards: checkpoints.convert_to_pngs.get(**wildcards).output,
        folder=directory("results/{folder}/{filename}"),
    output:
        touch("results/{folder}/{filename}.converted.flag"),


checkpoint all_converted:
    input:
        # file_list=get_uploaded_annotations_list,
        expand(
            "results/{folder}/{filename}.converted.flag",
            folder=folders,
            filename=filenames,
        ),
    output:
        touch("results/converted.flag"),


# checkpoint upload_annotations:
#     input:
#         "results/converted.flag"
#     output:
#         touch("results/uploaded.flag")


checkpoint convert_to_pngs:
    input:
        image=expand(
            "{data_dir}/{folder}/{filename}{file_suffix}",
            **config,
            allow_missing=True,
        )[0],
    output:
        temp(touch("results/{folder}/{filename}/converted.flag")),
        folder=directory("results/{folder}/{filename}"),
    script:
        "scripts/convert_to_pngs.py"
